// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Configurations;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(LastAuroraDbContext))]
    [Migration("20220405101326_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Model.Entities.AConvoyElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ELEMENT_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CODE");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("PRICE");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CONVOY_ELEMENTS");
                });

            modelBuilder.Entity("Model.Entities.Convoy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BackTruckId")
                        .HasColumnType("int")
                        .HasColumnName("BACK_TRUCK_ID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("CODE");

                    b.Property<int?>("FrontTruckId")
                        .HasColumnType("int")
                        .HasColumnName("FRONT_TRUCK_ID");

                    b.HasKey("Id");

                    b.HasIndex("BackTruckId")
                        .IsUnique();

                    b.HasIndex("FrontTruckId")
                        .IsUnique();

                    b.ToTable("CONVOY");
                });

            modelBuilder.Entity("Model.Entities.Addon", b =>
                {
                    b.HasBaseType("Model.Entities.AConvoyElement");

                    b.ToTable("ADDONS");
                });

            modelBuilder.Entity("Model.Entities.AUpgradableElement", b =>
                {
                    b.HasBaseType("Model.Entities.AConvoyElement");

                    b.Property<int?>("AddonId")
                        .HasColumnType("int")
                        .HasColumnName("ADDON_ID");

                    b.HasIndex("AddonId")
                        .IsUnique();

                    b.ToTable("UPGRADABLE_ELEMENTS");
                });

            modelBuilder.Entity("Model.Entities.Truck", b =>
                {
                    b.HasBaseType("Model.Entities.AUpgradableElement");

                    b.ToTable("TRUCKS");
                });

            modelBuilder.Entity("Model.Entities.Waggon", b =>
                {
                    b.HasBaseType("Model.Entities.AUpgradableElement");

                    b.Property<int?>("TruckId")
                        .HasColumnType("int")
                        .HasColumnName("TRUCK_ID");

                    b.HasIndex("TruckId");

                    b.ToTable("WAGGONS");
                });

            modelBuilder.Entity("Model.Entities.Convoy", b =>
                {
                    b.HasOne("Model.Entities.Truck", "BackTruck")
                        .WithOne()
                        .HasForeignKey("Model.Entities.Convoy", "BackTruckId");

                    b.HasOne("Model.Entities.Truck", "FrontTruck")
                        .WithOne()
                        .HasForeignKey("Model.Entities.Convoy", "FrontTruckId");

                    b.Navigation("BackTruck");

                    b.Navigation("FrontTruck");
                });

            modelBuilder.Entity("Model.Entities.Addon", b =>
                {
                    b.HasOne("Model.Entities.AConvoyElement", null)
                        .WithOne()
                        .HasForeignKey("Model.Entities.Addon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.AUpgradableElement", b =>
                {
                    b.HasOne("Model.Entities.Addon", "Addon")
                        .WithOne()
                        .HasForeignKey("Model.Entities.AUpgradableElement", "AddonId");

                    b.HasOne("Model.Entities.AConvoyElement", null)
                        .WithOne()
                        .HasForeignKey("Model.Entities.AUpgradableElement", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addon");
                });

            modelBuilder.Entity("Model.Entities.Truck", b =>
                {
                    b.HasOne("Model.Entities.AUpgradableElement", null)
                        .WithOne()
                        .HasForeignKey("Model.Entities.Truck", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.Waggon", b =>
                {
                    b.HasOne("Model.Entities.AUpgradableElement", null)
                        .WithOne()
                        .HasForeignKey("Model.Entities.Waggon", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Truck", "Truck")
                        .WithMany("Waggons")
                        .HasForeignKey("TruckId");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("Model.Entities.Truck", b =>
                {
                    b.Navigation("Waggons");
                });
#pragma warning restore 612, 618
        }
    }
}
